### ISSUE TITLE
sometimes, configure mask fails

### ISSUE THREAD

**Issue by beerockxs** [bstroebl/DataDrivenInputMask#28] opened 2019-05-10 12:01 UTC
Sometimes, configure mask fails on a selected vector layer with this python error:

Traceback (most recent call last):
              File "C:/Users/sebastian.brocks/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\datadriveninputmask.py", line 317, in configureMask
              self.app.ddManager.showFeatureForm(configLayer, forFeature)
              File "C:/Users/sebastian.brocks/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddmanager.py", line 452, in showFeatureForm
              title = title)
              File "C:/Users/sebastian.brocks/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\dddialog.py", line 60, in __init__
              self.initialize()
              File "C:/Users/sebastian.brocks/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\dddialog.py", line 81, in initialize
              self.ui.initialize(self.layer, self.feature, self.db, self.mode)
              File "C:/Users/sebastian.brocks/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddui.py", line 1213, in initialize
              aForm.initialize(layer, feature, db, mode)
              File "C:/Users/sebastian.brocks/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddui.py", line 1360, in initialize
              self.oldSubsetString = self.layer.subsetString()
             RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted

**Comment by bstroebl** [comment] 2019-05-13 06:46
Hi,
I never experienced this problem. Any additional information you can give me? Has configuration worked before in this QGIS session? Did you remove any layers from the project before this happened?

**Comment by beerockxs** [comment] 2019-05-13 14:03
In a session when the bug occured, configuration did work previously. I did not remove layers before the bug happened.

**Comment by bstroebl** [comment] 2019-05-13 14:14
Strange, the Python error suggests that a layer that used to be in the project is not existing any more. I suspect it is either `dd_table`, `dd_tab` or `dd_field` which are the layers that store the configuration. Can you reproduce the error or is it happening randomly?

**Comment by beerockxs** [comment] 2019-05-14 13:47
It is pretty much random, sometimes it happens lots of times in one day, other days not at all.

**Comment by bstroebl** [comment] 2019-05-14 14:12
It is hard to debug errors that cannot be reproduced. Do you get the same error
`RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted`
when you edit any of your regular layers or just with the config layer?

**Comment by bstroebl** [comment] 2020-05-18 10:42
can we close this?

**Comment by bstroebl** [comment] 2022-11-08 07:32
closed due to lack of feedback

**Closed by bstroebl** 2022-11-08 07:32 UTC
Labels: bug, wontfix
